version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://backend:3000
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Aepppa20yseeuf
      DB_NAME: fantasticgroup
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aepppa20yseeuf
      MYSQL_DATABASE: fantasticgroup
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
