version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://backend:3000 
    ports:
      - "80:80"  
    depends_on:
      - backend
    networks:
      - fantastic-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Aepppa20yseeuf
      DB_NAME: fantastic_db
    depends_on:
      - db
    networks:
      - fantastic-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 5

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: fantastic_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fantastic-network

volumes:
  db_data:

networks:
  fantastic-network:
    driver: bridge
